### PR TITLE
Add new words

### PR DESCRIPTION
**Pull request by filipekiss**
Also sorts everything alphabetically.

Some words were misplaced, so I just sorted everything again after adding my words. :)

### CODE REVIEW

**Comment by filipekiss** [comment]
I'm not sure about `caralhada` being a bad word so I put it anyway, but if you think I should remove it just say so. :)

**Comment by rafaelrinaldi** [comment]
Hey @filipekiss thanks for contributing! "bilboque" <3

Yeah, just please remove `caralhada` since it can be considered a bad word.

:beers:

**Comment by filipekiss** [comment]
Hey @rafaelrinaldi, I think everything is fine, now. :) Let me know if you need anything else.

**Comment by rafaelrinaldi** [comment]
@filipekiss :ship:

**Pull request merged**
