### PR TITLE
Adds uma caralhada de words

### PR DESCRIPTION
**Pull request by joaocunha**
Some improvements to this buçanha.

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
@joaocunha Thanks for contributing! Can you please remove the non-ascii characters?

**Comment by joaocunha** [comment]
Sure, hold on.

**Comment by joaocunha** [comment]
@rafaelrinaldi there you go.

**Comment by rafaelrinaldi** [comment]
@joaocunha Would you mind fixing the merge conflict as well?

**Comment by joaocunha** [comment]
Done.

**Comment by rafaelrinaldi** [comment]
@joaocunha You're officially awesome :muscle:

**Pull request merged**
