### PR TITLE
added the words COCORAS, ESTROVENGA, BUGIGANGA, and PINICO

### PR DESCRIPTION
**Pull request by Ghostavio**
Added the word [**cócoras**](https://pt.wiktionary.org/wiki/c%C3%B3coras), probably the funniest Brazilian word ever, which stands for **squat** in english, usually used to perform a number two in the jungle (and then cleaning yourself with a banana leaf).

Also added the word [**estrovenga**](http://www.dicionarioinformal.com.br/estrovenga/), which has so many meanings and it apparently is some kind of [tool](https://www.google.com.br/search?q=estrovenga&espv=2&biw=1440&bih=801&tbm=isch&tbo=u&source=univ&sa=X&ved=0CCUQsARqFQoTCI-pkfCMtscCFcoLkAodqpINQA&dpr=1) to cut sugar cane, but it's mostly used as a slang for _dick_ on the internet (world wide web).

The word [**bugiganga**](http://www.dicionarioinformal.com.br/bugiganga/) is a synonym to _estrovenga_ or _cacareco_, and it was made famous by the _Inspector Gadget_ cartoon, which translates to _Inspetor Bugiganga_.

At least but not last, the word [**pinico**](http://www.dicionarioinformal.com.br/pinico/), which is a small pot old people have under the bed to pee at night. We once said this word to a Lebanese friend and she still thinks it's the best word in our whole language.

### CODE REVIEW

**Comment by rafaelrinaldi** [comment]
@Ghostavio Dude, thanks a lot! That's awesome :sparkling_heart: 

"estrovenga" is a first for me.

**Comment by Ghostavio** [comment]
You're welcome dude, amazing lib right here :p

**Comment by Ghostavio** [comment]
"estrovenga" is also a synonym for "cacareco" or "bugiganga" (this one is not in the list yet btw - let me quickly add it before you merge this)

**Comment by rafaelrinaldi** [comment]
awesome

**Comment by Ghostavio** [comment]
done

**Comment by diessica** [comment]
Loved this PR! Bugiganga, cacareco <3

**Pull request merged**
